# Generated by Django 2.0.2 on 2018-02-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
