# Generated by Django 2.0.2 on 2018-02-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180220_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='kind',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='app_name',
            field=models.CharField(max_length=150),
        ),
    ]
