# Generated by Django 2.0.2 on 2018-02-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180222_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_name',
            field=models.CharField(max_length=200),
        ),
    ]
